version: "3"

env:
  AWS_SAM_DIR: .aws-sam
  BUILD_DIR: "{{.AWS_SAM_DIR}}/build"
  STACK: slchess

dotenv:
  - ./configs/aws/base.env
  - ./configs/aws/cognito.env

includes:
  cognito:
    taskfile: ./taskfiles/Cognito.yml
    dir: .
  stack: ./taskfiles/Stack.yml
  server: ./taskfiles/Server.yml
  env: ./taskfiles/Env.yml
  doc: ./taskfiles/Doc.yml
