version: "3"

tasks:
  server-up:
    preconditions:
      - test -f compose.yml
    cmds:
      - docker compose up --build

  server-down:
    preconditions:
      - test -f compose.yml
    cmds:
      - docker compose down

  server-local:
    cmds:
      - go mod download
      - go run ./cmd/server/

  test:
    cmds:
      - go test -v ./...

  fmt:
    cmds:
      - go fmt ./...

  lint:
    cmds:
      - govulncheck
      - golangci-lint run
