version: "3"

env:
  AWS_SAM_DIR: .aws-sam
  BUILD_DIR: "{{.AWS_SAM_DIR}}/build"
  AWS_REGION: ap-southeast-2
  STACK: slchess

tasks:
  deploy:
    cmds:
      - sam deploy --guided --region $AWS_REGION --config-file samconfig.yaml

  remove:
    cmds:
      - sam delete --region $AWS_REGION --config-file samconfig.yaml

  sync:
    cmds:
      - sam sync --stack-name $STACK --watch

  build:
    vars:
      HANDLERS: [ConnectFunction, DisconnectFunction, MatchmakingFunction]
    cmds:
      - sam build --region $AWS_REGION --config-file samconfig.yaml
      - for: { var: HANDLERS }
        cmd: chmod +x $BUILD_DIR/{{.ITEM}}/bootstrap

  server-up:
    preconditions:
      - test -f compose.yml
    cmds:
      - docker compose up --build
  server-down:
    preconditions:
      - test -f compose.yml
    cmds:
      - docker compose down

  server-local:
    cmds:
      - go mod download
      - go run ./cmd/server/

  clean:
    cmds:
      - rm -rf $AWS_SAM_DIR ./bin

  test:
    cmds:
      - go test -v ./...

  fmt:
    cmds:
      - go fmt ./...

  lint:
    cmds:
      - govulncheck
      - golangci-lint run
