version: "3"

env:
  AWS_SAM_DIR: .aws-sam
  BUILD_DIR: "{{.AWS_SAM_DIR}}/build"

tasks:
  deploy:
    cmds:
      - sam deploy --guided --region $AWS_REGION --config-file samconfig.yaml

  build:
    vars:
      HANDLERS:
        [
          ConnectFunction,
          DisconnectFunction,
          MakeMoveFunction,
          StartGameFunction,
        ]
    cmds:
      - sam build --region $AWS_REGION --config-file samconfig.yaml
      - for: { var: HANDLERS }
        cmd: chmod +x $BUILD_DIR/{{.ITEM}}/bootstrap

  clean:
    cmds:
      - rm -rf $AWS_SAM_DIR

  test:
    cmds:
      - go test -v ./...

  fmt:
    cmds:
      - go fmt ./...

  lint:
    cmds:
      - govulncheck
      - golangci-lint run
