AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: WebSocket-based Chess Game Backend

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  ### Cognito User Pool ###
  SlchessUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: SlchessUserPool
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true

  SlchessUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: SlchessUserPoolClient
      UserPoolId: !Ref SlchessUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  ### SNS Topic ###
  SlchessSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MatchmakingNotification

  ### Websocket API ###
  SlchessWebsocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SlchessWebsocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SlchessWebsocket
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub "integrations/${ConnectIntegration}"
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SlchessWebsocket
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectFunction.Arn}/invocations"

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SlchessWebsocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub "integrations/${DisconnectIntegration}"
  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SlchessWebsocket
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DisconnectFunction.Arn}/invocations"

  # WebSocket API Deployment
  SlchessDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref SlchessWebsocket
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
  SlchessStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref SlchessWebsocket
      DeploymentId: !Ref SlchessDeployment
      StageName: dev

  ### HTTP API ###
  SlchessApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SlchessApi
      StageName: prod
      Cors: "'*'"
      Auth:
        Authorizers:
          SlchessAuth:
            UserPoolArn: !GetAtt SlchessUserPool.Arn
        DefaultAuthorizer: SlchessAuth

  ### Lambda Functions ###
  ConnectFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/lambda/connect/
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Connections
      Environment:
        Variables:
          TABLE_NAME: Connections
          COGNITO_USER_POOL_ID: !Ref SlchessUserPool

  DisconnectFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/lambda/disconnect/
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Connections
      Environment:
        Variables:
          TABLE_NAME: Connections

  MatchmakingFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/lambda/matchmaking/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 10
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SlchessSNSTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: Connections
        - DynamoDBCrudPolicy:
            TableName: MatchmakingTickets
        - DynamoDBCrudPolicy:
            TableName: UserMatches
        - DynamoDBCrudPolicy:
            TableName: ActiveMatches
      VpcConfig:
        SecurityGroupIds:
          - sg-003fd8c2326289ec4
        SubnetIds:
          - subnet-08afaaea0b1e4f825
          - subnet-0f7183aa53381f50c
          - subnet-0642049eeace8e1b3
      Environment:
        Variables:
          CACHE_NAME: SlchessCache
          SNS_TOPIC_ARN: !Ref SlchessSNSTopic
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /matchmaking
            Method: post
            RestApiId: !Ref SlchessApi

  ### DynamoDB Tables ###
  Connections:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Connections
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  UserMatches:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserMatches
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  MatchmakingTickets:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MatchmakingTickets
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ActiveMatches:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ActiveMatches
      AttributeDefinitions:
        - AttributeName: MatchId
          AttributeType: S
      KeySchema:
        - AttributeName: MatchId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  MatchStates:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: MatchStates
      PrimaryKey:
        Name: MatchId
        Type: String

  MatchRecords:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MatchRecords
      AttributeDefinitions:
        - AttributeName: MatchId
          AttributeType: S
      KeySchema:
        - AttributeName: MatchId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  SlchessWebSocketUrl:
    Value: !Sub "wss://${SlchessWebsocket}.execute-api.${AWS::Region}.amazonaws.com/dev"
    Description: WebSocket API endpoint
