AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Root Stack for Slchess Backend

Parameters:
  ServerImageUri:
    Type: String
    Description: "URI of the Docker image for game server in ECR"
  DeploymentStage:
    Type: String
    Default: dev

Resources:
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/storage.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        DeploymentStage: !Ref DeploymentStage

  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/auth.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        DeploymentStage: !Ref DeploymentStage
    DependsOn: StorageStack

  AppSyncStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/appsync.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        DeploymentStage: !Ref DeploymentStage
    DependsOn:
      - StorageStack
      - AuthStack

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/compute.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        ServerImageUri: !Ref ServerImageUri
        DeploymentStage: !Ref DeploymentStage
    DependsOn:
      - StorageStack
      - AuthStack
      - AppSyncStack

  WebsocketApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/websocketApi.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        DeploymentStage: !Ref DeploymentStage
    DependsOn:
      - StorageStack
      - AuthStack
      - ComputeStack

  HttpApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/httpApi.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        DeploymentStage: !Ref DeploymentStage
    DependsOn:
      - StorageStack
      - AuthStack
      - AppSyncStack
      - ComputeStack
      - WebsocketApiStack

  LogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/log.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        DeploymentStage: !Ref DeploymentStage

Outputs:
  AppSyncGraphQLApiUrl:
    Description: AppSync GraphQL API endpoint URL
    Value: !GetAtt AppSyncStack.Outputs.AppSyncGraphQLApiUrl

  AppSyncRealtimeApiUrl:
    Description: AppSync API real-time endpoint URL
    Value: !GetAtt AppSyncStack.Outputs.AppSyncRealtimeApiUrl

  WebsocketApiUrl:
    Description: WebSocket API URL
    Value: !GetAtt WebsocketApiStack.Outputs.WebsocketApiUrl

  MatchmakingEndpointUrl:
    Description: "Endpoint URL for matchmaking"
    Value: !Sub "${HttpApiStack.Outputs.HttpApiEndpoint}/matchmaking"

  UserGetEndpointUrl:
    Description: "Endpoint URL for get user information"
    Value: !Sub "${HttpApiStack.Outputs.HttpApiEndpoint}/user"

  MatchRecordGetEndpointUrl:
    Description: "Endpoint URL for get a single match record"
    Value: !Sub "${HttpApiStack.Outputs.HttpApiEndpoint}/match/{id}"

  MatchResultListEndpointUrl:
    Description: "Endpoint URL for get a list of match results"
    Value: !Sub "${HttpApiStack.Outputs.HttpApiEndpoint}/matchResults?limit=5&startKey=<START-KEY>"

  MatchStateListEndpointUrl:
    Description: "Endpoint URL for get a list of match results"
    Value: !Sub "${HttpApiStack.Outputs.HttpApiEndpoint}/match/{id}/states?limit=20&startKey=<START-KEY>&order=asc"

  ActiveMatchListEndpointUrl:
    Description: "Endpoint URL for get a list of active matches"
    Value: !Sub "${HttpApiStack.Outputs.HttpApiEndpoint}/activeMatches?limit=5&startKey=<START-KEY>"

  UserRatingListEndpointUrl:
    Description: "Endpoint URL for get a list of user ratings"
    Value: !Sub "${HttpApiStack.Outputs.HttpApiEndpoint}/userRatings?limit=5&startKey=<START-KEY>"

  RestoreMatchEndpointUrl:
    Description: "Endpoint URL for restoring a match"
    Value: !Sub "${HttpApiStack.Outputs.HttpApiEndpoint}/match/{id}/restore"

  SpectateMatchEndpointUrl:
    Description: "Endpoint URL for spectating a match"
    Value: !Sub "${HttpApiStack.Outputs.HttpApiEndpoint}/match/{id}/spectate"
