AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: WebSocket-based Chess Game Backend

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  # WebSocket API
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ChessWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  # WebSocket API Deployment
  WebSocketApiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref WebSocketApi
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - MakeMoveRoute

  WebSocketApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      DeploymentId: !Ref WebSocketApiDeployment
      StageName: dev

  # Connect Route
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub "integrations/${ConnectIntegration}"

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectFunction.Arn}/invocations"

  # Disconnect Route
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub "integrations/${DisconnectIntegration}"

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DisconnectFunction.Arn}/invocations"

  # Connect Lambda Function
  ConnectFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/connect/
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - DynamoDBCrudPolicy:
            TableName: WebSocketConnections
      Environment:
        Variables:
          TABLE_NAME: WebSocketConnections

  # Disconnect Lambda Function
  DisconnectFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/disconnect/
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - DynamoDBCrudPolicy:
            TableName: WebSocketConnections
      Environment:
        Variables:
          TABLE_NAME: WebSocketConnections

  # DynamoDB Table for WebSocket Connections
  Connections:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Connections
      AttributeDefinitions:
        - AttributeName: ConnectionId
          AttributeType: S
      KeySchema:
        - AttributeName: ConnectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # DynamoDB Table for Sessions
  Sessions:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Sessions
      AttributeDefinitions:
        - AttributeName: SessionId
          AttributeType: S
      KeySchema:
        - AttributeName: SessionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: SessionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ActiveGames:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ActiveGames
      AttributeDefinitions:
        - AttributeName: GameId
          AttributeType: S
      KeySchema:
        - AttributeName: GameId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GameRecords:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GameRecords
      AttributeDefinitions:
        - AttributeName: GameId
          AttributeType: S
      KeySchema:
        - AttributeName: GameId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GameStates:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GameRecords
      AttributeDefinitions:
        - AttributeName: GameId
          AttributeType: S
      KeySchema:
        - AttributeName: GameId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  WebSocketApiUrl:
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
    Description: WebSocket API endpoint
