version: "3"

env:
  AWS_SAM_DIR: .aws-sam
  BUILD_DIR: "{{.AWS_SAM_DIR}}/build"
  STACK: slchess

includes:
  utils:
    taskfile: ./Util.yml
    internal: true
    dir: ../

tasks:
  output:
    desc: Print stack output to json file
    cmds:
      - sam list stack-outputs --stack-name slchess --output json

  deploy:
    desc: Deploy the current local stack on AWS
    deps: [utils:check-base-env]
    cmds:
      - task: build
      - sam deploy
        --stack-name $STACK
        --region $AWS_REGION
        --parameter-overrides "ServerImageUri=$SERVER_IMAGE_URI"
        --confirm-changeset
        --capabilities CAPABILITY_NAMED_IAM
        --no-disable-rollback
        --config-file samconfig.yaml
        --config-env default

  remove:
    desc: Remove the stack from AWS
    deps: [utils:check-base-env]
    cmds:
      - sam delete --region $AWS_REGION --config-file samconfig.yaml
      - rm ./configs/aws/*.env

  sync:
    desc: Sync the stack
    cmds:
      - sam sync --stack-name $STACK --watch

  build:
    desc: Build the stack
    deps: [utils:check-base-env]
    vars:
      HANDLERS:
        - ConnectFunction
        - DisconnectFunction
        - QueueingFunction
        - PostUserConfirmationFunction
        - EndGameFunction
        - MatchmakingFunction
        - MatchRecordGetFunction
        - MatchResultListFunction
        - MatchStateListFunction
        - ActiveMatchListFunction
        - UserRatingListFunction
        - MatchRestoreFunction
        - MatchSpectateFunction
    cmds:
      - sam build --region $AWS_REGION --config-file samconfig.yaml
      - for: { var: HANDLERS }
        cmd: chmod +x $BUILD_DIR/{{.ITEM}}/bootstrap
